name: Build

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@47be81e60ed1d891c696c3fb7f558876ba9a2b57 # v3.2.0
        with:
          node-version: 24.x
