on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: release-please
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    environment:
      name: prod

    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - uses: linz/action-typescript@9bf69b0f313b3525d3ba3116f26b1aff7eb7a6c0 # v3.1.0
        with:
          node-version: 23.x

      - name: (Prod) Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: (Prod) Deploy
        run: |
          npx cdk deploy --require-approval never
        env:
          NODE_ENV: 'production'
          CACHE_BUCKET_NAME: 'linz-lds-cache'
